spring:
  datasource:
    url: jdbc:mysql://localhost:3306/musicstore
    username: musicstore
    password: 12345
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create-drop
